# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 06:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0002_auto_20170218_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbuser',
            name='user_type',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='fbuser',
            name='user_id',
            field=models.SlugField(default='', max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
