# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 21:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mcbot', '0004_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbuser',
            name='code',
            field=models.SlugField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fbuser',
            name='authentication_status',
            field=models.CharField(default='authentication_no', max_length=20),
        ),
        migrations.AddField(
            model_name='fbuser',
            name='mcgill_email',
            field=models.EmailField(default='', max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid McGill email address.', whitelist='mcgill.ca')]),
        ),
    ]
