# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McGillEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=70)),
                ('event_date', models.DateTimeField()),
                ('event_link', models.URLField()),
            ],
        ),
    ]
