# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_mcgill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcgillevent',
            name='event_link',
            field=models.URLField(blank=True),
        ),
    ]
