# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_mcgill', '0002_auto_20170302_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcgillevent',
            name='event_type',
            field=models.CharField(choices=[('event_academic', 'Academic Deadlines'), ('event_facebook', 'Facebook Event'), ('event_misc', 'Misc')], default='event_academic', max_length=70),
        ),
    ]
